apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 7981689475/boutique-auth:8935a3de13cda7d63a81fd6b77925f9e1e000100
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: AUTH_DB_URL

--- 

apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: boutique
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
