name: Boutique CI Pipeline

on: 
 push:
   branches:
     - dev

 pull_request:
   branches:
     - dev

jobs:
  build:
    runs-on: self-hosted

    steps: 
      - name: checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Verify Node
        run: |
          node -v
          npm  -v

      - name: Install Dependencies 
        working-directory: projects/boutique-microservices
        run: npm ci

      - name: Build Project 
        working-directory:  projects/boutique-microservices
        run: npm run build



