name: Boutique CI Pipeline

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  detect-changes:
    runs-on: self-hosted

    outputs:
      services: ${{ steps.changed.outputs.services }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Changed Services
        id: changed
        shell: bash
        run: |
          git fetch origin dev

          CHANGED_FILES=$(git diff --name-only origin/dev...HEAD)

          echo "Changed Files:"
          echo "$CHANGED_FILES"

          SERVICES=()

          BACKEND_SERVICES=(
            auth
            gateway
            orders
            order-service
            product-service
            user-service
          )

          for SERVICE in "${BACKEND_SERVICES[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^projects/boutique-microservices/backend/services/${SERVICE}/"; then
              SERVICES+=("\"$SERVICE\"")
            fi
          done

          if echo "$CHANGED_FILES" | grep -q "^projects/boutique-microservices/frontend/"; then
            SERVICES+=("\"frontend\"")
          fi

          JSON="[$(IFS=,; echo "${SERVICES[*]}")]"

          echo "Detected Services: $JSON"

          echo "services=$JSON" >> "$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.service }}

    needs: detect-changes

    if: needs.detect-changes.outputs.services != '[]'

    runs-on: self-hosted

    strategy:
      fail-fast: false

      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Trivy Filesystem Scan
        run: |
          trivy fs \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            projects/boutique-microservices

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Build Path
        id: buildpath
        shell: bash
        run: |
          if [ "${{ matrix.service }}" = "frontend" ]; then
            echo "path=projects/boutique-microservices/frontend" >> $GITHUB_OUTPUT
          else
            echo "path=projects/boutique-microservices/backend/services/${{ matrix.service }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker Image
        run: |
          docker build \
            -t boutique-${{ matrix.service }}:${{ github.sha }} \
            ${{ steps.buildpath.outputs.path }}

      - name: Trivy Image Scan
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            boutique-${{ matrix.service }}:${{ github.sha }}

      - name: Tag Docker Image
        run: |
          docker tag \
            boutique-${{ matrix.service }}:${{ github.sha }} \
            ${{ secrets.DOCKER_USERNAME }}/boutique-${{ matrix.service }}:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/boutique-${{ matrix.service }}:${{ github.sha }}


  update-manifests:
    name: Update Kubernetes Manifests

    needs:
      - detect-changes
      - build

    if: >
      github.event_name == 'push' &&
      needs.detect-changes.outputs.services != '[]'

    runs-on: self-hosted

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOUTIQUE_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update Changed Manifests
        shell: bash
        run: |
          TAG=${{ github.sha }}
          USERNAME=${{ secrets.DOCKER_USERNAME }}

          SERVICES='${{ needs.detect-changes.outputs.services }}'

          echo "$SERVICES" | jq -r '.[]' | while read SERVICE
          do
            echo "Updating $SERVICE"

            if [ "$SERVICE" = "frontend" ]; then
              FILE="gitops/k8s/frontend/deployment.yml"
            else
              FILE="gitops/k8s/backend/${SERVICE}.yml"
            fi

            sed -i "s|image:.*|image: ${USERNAME}/boutique-${SERVICE}:${TAG}|g" "$FILE"

          done

      - name: Commit Changes
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add gitops/

          if git diff --cached --quiet
          then
            echo "No manifest changes."
          else
            git commit -m "Update image tags to ${{ github.sha }}"
            git push
          fi
