name: Boutique CI Pipeline

on: 
 push:
   branches:
     - dev

 pull_request:
   branches:
     - dev

jobs:
  build:
    runs-on: self-hosted

    steps: 
      - name: checkout Repository
        uses: actions/checkout@v4

      - name: Print Environment
        run: |
          echo "Runner Information"
          hostname
          pwd
          whoami

      - name: Verify Git
        run: git --version

      - name: Verify Docker
        run: docker --version

      - name: verify Kubectl
        run: kubectl version --client

      - name: Verify Helm
        run: helm version
 
      - name: Verify Node
        run: node --version

      - name: verify NPM
        run: npm --version

      - name: Milestone 1 Completed
        run: echo "CI Foundation is working"

            
